### ISSUE TITLE
El component en el ejemplo esta in minus

### ISSUE THREAD

**Issue by jesusgoku** [claudioDcv/Table2ReactDjangoREST#3]
- En el ejemplo el componente sale un minus.
- En el ejemplo mostrar como se importa la librería.
- Dejar claro como primer párrafo el alcance del componente. Para ser usada con el paginador personalizado de Django y referencias en el futuro a ese componente en su proyecto.

Work in progress ...

**Comment by claudioDcv** [comment]
Listo don Jesus done
